import Wordmark from '../common/Wordmark'

const DISCLOSURES = [
  {
    title: 'Data Variance',
    body: 'Market data may vary slightly across different providers.',
  },
  {
    title: 'AI Analysis',
    body: 'Insights are generated by a multi-agent reasoning engine. While designed for logic and structure, AI outputs may contain errors or hallucinate market context.',
  },
  {
    title: 'Not Financial Advice',
    body: 'Tradable Mind is a research and reasoning tool. It does not provide financial advice or trade execution. Never invest based solely on AI-generated analysis.',
  },
]

export default function Footer() {
  return (
    <footer className="mb-12 mt-20 border-t pt-8" style={{ borderColor: 'var(--border)' }}>
      <div className="flex items-center justify-between">
        <Wordmark size={22} />
        <span className="text-xs" style={{ color: 'var(--text-faint)' }}>
          © {new Date().getFullYear()} Tradable Mind
        </span>
      </div>

      <div className="mt-8 grid grid-cols-1 gap-x-8 gap-y-5 sm:grid-cols-3">
        {DISCLOSURES.map((d) => (
          <div key={d.title}>
            <p className="text-[0.78rem] font-semibold" style={{ color: 'var(--text)' }}>
              {d.title}
            </p>
            <p className="mt-1 text-[0.78rem] leading-relaxed" style={{ color: 'var(--text-faint)' }}>
              {d.body}
            </p>
          </div>
        ))}
      </div>
    </footer>
  )
}
