import Wordmark from '../common/Wordmark'

const DISCLOSURES = [
  {
    icon: 'database',
    title: 'Data Variance',
    body: 'Market data may vary slightly across different providers.',
  },
  {
    icon: 'neurology',
    title: 'AI Analysis',
    body: 'Insights are generated by a multi-agent reasoning engine. While designed for logic and structure, AI outputs may contain errors or hallucinate market context.',
  },
  {
    icon: 'gavel',
    title: 'Not Financial Advice',
    body: 'Tradable Mind is a research and reasoning tool. It does not provide financial advice or trade execution. Never invest based solely on AI-generated analysis.',
  },
]

export default function Footer() {
  return (
    <footer className="mt-24 mb-14 border-t pt-10" style={{ borderColor: 'var(--border)' }}>
      <div className="mb-6 flex items-center justify-between">
        <Wordmark size={24} />
        <span className="text-xs" style={{ color: 'var(--text-faint)' }}>
          © {new Date().getFullYear()} Tradable Mind
        </span>
      </div>

      <div className="tm-card p-6 sm:p-7">
        <h4
          className="font-display mb-5 text-base font-bold"
          style={{ color: 'var(--text)' }}
        >
          Transparency &amp; Risk Disclosure
        </h4>
        <div className="grid grid-cols-1 gap-5 sm:grid-cols-3">
          {DISCLOSURES.map((d) => (
            <div key={d.title}>
              <div className="mb-2 flex items-center gap-2">
                <span
                  className="material-symbol"
                  style={{ fontSize: 18, color: 'var(--brand)' }}
                >
                  {d.icon}
                </span>
                <span className="text-sm font-semibold" style={{ color: 'var(--text)' }}>
                  {d.title}
                </span>
              </div>
              <p className="text-[0.82rem] leading-relaxed" style={{ color: 'var(--text-muted)' }}>
                {d.body}
              </p>
            </div>
          ))}
        </div>
      </div>
    </footer>
  )
}
